version: 3

dotenv: ['custom.env', 'default.env']

tasks:
  default:
    desc: List all tasks
    cmds:
      - task -l

  install:
    desc: Install all project dependencies
    cmds:
      - poetry install

  graph:pull:
    desc: Pull graph file from Repo
    cmds:
      - mkdir -p graphs
      - curl -L -o "{{.GRAPH_FILE}}" "{{.GRAPH_FILE_URL}}"

  build:
    desc: Build the site
    cmds:
      - poetry run mkdocs build

  serve:
    desc: Serve the site
    cmds:
      - poetry run mkdocs serve

  serve:endpoint:
    desc: Serve the data endpoint
    summary: Serve the data with [sparql-file](https://github.com/AKSW/sparql-file)
    cmds:
      - sparql-file --port 8080 ./graphs/awesome.ttl

  hack:webarchive:env:
    desc: Setup env
    summary: These changes are temporary adjustments for the webarchive setup and should be replaced by better solutions in the future
    cmd: |
      ln -s webarchive.env custom.env

  hack:webarchive:prefix:
    desc: Setup prefix
    summary: There is a propper prefix management for mkrdf missing, but dcterms is needed in the templates
    cmd: |
      sed -i '2s;^;@prefix dcterms: <http://purl.org/dc/terms/> .\n;' "{{ .GRAPH_FILE }}"


  ci:
    desc: The CI task
    cmds:
      - task: install
      - task: graph:pull
      - task: hack:webarchive:prefix
      - env
      - cat "{{ .GRAPH_FILE }}"
      - task: build