version: 3

tasks:
  default:
    desc: List all tasks
    cmds:
      - task -l

  install:
    desc: Install all project dependencies
    cmds:
      - poetry install

  graph:pull:
    desc: Pull graph file from Repo
    cmds:
      - python3 ./scripts/graph_pull.py "{{.URL}}"

  build:
    desc: Build the site
    cmds:
      - poetry run mkdocs build

  serve:
    desc: Serve the site
    cmds:
      - poetry run mkdocs serve

  serve:endpoint:
    desc: Serve the data endpoint
    summary: Serve the data with [sparql-file](https://github.com/AKSW/sparql-file)
    cmds:
      - sparql-file --port 8080 ./graphs/awesome.ttl
