version: 3

tasks:
  default:
    desc: List all tasks
    cmds:
      - task -l

  install:
    desc: Install all project dependencies
    cmds:
      - poetry install

  graph:pull:webarchive:
    desc: Download the webarchiv graph file
    cmds:
      - task: graph:pull
        vars:
          URL: https://raw.githubusercontent.com/deutsche-nationalbibliothek/webarchiving-awesome-graph/refs/heads/main/graphs/awesome.ttl

  graph:pull:aksw:
    desc: Download the aksw graph file
    cmds:
      - task: graph:pull
        vars:
          URL: https://raw.githubusercontent.com/anastasiautomo/aksw-awesome-graph/refs/heads/Develop/graphs/awesome.ttl

  graph:pull:
    desc: Pull graph file from Repo
    cmds:
      - mkdir -p graphs
      - curl -L -o graphs/awesome.ttl "{{.URL}}"

  build:
    desc: Build the site
    cmds:
      - poetry run mkdocs build

  serve:
    desc: Serve the site
    cmds:
      - poetry run mkdocs serve

  serve:endpoint:
    desc: Serve the data endpoint
    summary: Serve the data with [sparql-file](https://github.com/AKSW/sparql-file)
    cmds:
      - sparql-file --port 8080 ./graphs/awesome.ttl
