CONSTRUCT {
  ?item a doap:Project ;
        dc:title ?label ;
        dc:description ?desc ;
        doap:homepage ?homepage ;
        dc:subject ?category ;
        dc:type doap:Project ;
        doap:repository ?repo .
}
WHERE {
  ?item a doap:Project ;
        rdfs:label ?label ;
        doap:category ?category .

  OPTIONAL { ?item dct:description ?desc }
  OPTIONAL { ?item doap:homepage ?homepage }
  OPTIONAL { ?item doap:repository ?repo }

}